### ISSUE TITLE
Testing RxJS ajax fetch

### ISSUE THREAD

**Issue by MrRoyce** [jeffbski/redux-logic-test#1]
Hi there, I'm having some issues setting up a test of a mocked RxJS ajax fetch client.

Here is the logic:

```javascript
export const getCategoriesLogic = createLogic({
  type           : LIST_CATEGORIES,
  latest         : true, 
  processOptions : {
    dispatchReturn : true,
    successType    : getCategoriesSuccess,
    failType       : getCategoriesFailure
  },

  process({ httpClient, CAT_API }) {
    return httpClient({ url : `${CAT_API.url}/categories`, crossDomain: true})
    .map(payload => payload) 
    .catch((err) => {
      console.log('Error on getting categories: ' + err);
    });
  }
});
```

Here is the test (simplified):
```javascript
const categories = [
    { name : 'test1'}
  ];

const injectedDeps = { 
  httpClient : () => {  // Here is the attempt at mocking the RxJS ajax client!
      return {
        map   : () => {  Promise.resolve(categories); },
        catch : () => {}
    };
  },
  CAT_API : {
    url : 'http://test.com'
  }
};

const store = createMockStore({
  initialState : {},
  reducer,  // imported reducer
  logic : [getCategoriesLogic],  // imported logic
  injectedDeps
});

it('gets the correct categories', () => {
  store.dispatch({ type: LIST_CATEGORIES }); 
  store.whenComplete(() => {
    expect(store.actions).toEqual([
      { type: LIST_CATEGORIES },
      { type: LIST_CATEGORIES_SUCCESS, payload: categories }
    ]);
  });
});
```

I get the error:
```
console.error node_modules/redux-logic/build-lib/createLogicAction$.js:280

unhandled exception in logic named: L(LIST_CATEGORIES)-0 [TypeError: Cannot read property 'catch' of undefined]
```

I'm probably not setting up the http client and promise correctly.  Any ideas on where I went wrong?

regards,
Royce

**Comment by MrRoyce** [comment]
I tried the httpClient as found in 

https://github.com/jeffbski/redux-logic/blob/master/examples/async-rxjs-ajax-proc-options/test/users-fetch-logic.spec.js

```javascript
const httpClient = () => {
  return Observable.of({ // match shape of reqres.in api
    data: [{ id: 1 }],
    map: () => {}
  });
};
```
The test passes, but I dont think its correct because it always passes no matter what I use for the expected payload!!

**Comment by jeffbski** [comment]
Yes, to mock out the RxJS ajax client, you can just create a fn that returns an observable like

```js
const httpClient = () => {
  return Observable.of({ // match shape of your api results
    data: [{ id: 1 }]
  });
};
```

You don't need to implement map and catch in that since the Observable.of gives you all those methods. 

And obviously for different types of tests you can have it return different things or even use Observable.throw(err) to have it simulate an error instead of success.

The other thing you need to do is to wait in the test for it to complete before continuing so you can either return the promise that comes from store.whenComplete or add a `done` which is probably clearer.

```js
it('gets the correct categories', done => {  // <-- add done when doing async tests
  store.dispatch({ type: LIST_CATEGORIES }); 
  store.whenComplete(() => {
    expect(store.actions).toEqual([
      { type: LIST_CATEGORIES },
      { type: LIST_CATEGORIES_SUCCESS, payload: categories }
    ]);
    done(); // call this when finished with all our verifications
  });
});
```

Alternatively if you want to just return the promise you can do

```js
it('gets the correct categories', () => {  
  store.dispatch({ type: LIST_CATEGORIES }); 
  return store.whenComplete(() => { // <----- by returning the promise the test will wait until it is done
    expect(store.actions).toEqual([
      { type: LIST_CATEGORIES },
      { type: LIST_CATEGORIES_SUCCESS, payload: categories }
    ]);
  });
});
```

Either way will work it is a matter of preference. The `done` is probably more visible.

Hopefully that will get you working, but let me know if more questions.

**Comment by MrRoyce** [comment]
I tried both methods, but they both fail with 
```
 Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
```

I tried adding a timeout value of 10000 as in 

http://stackoverflow.com/questions/9867601/how-do-i-change-the-timeout-on-a-jasmine-node-async-spec

And I also tried adding a src/setupTests.js with 
```
jasmine.DEFAULT_TIMEOUT_INTERVAL = 10000;
```

As in https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#initializing-test-environment

I'm using create-react-app for this project, which uses jest/Jasmine which just adds to the complexity/misery factor ;-)

arrgghh!

**Comment by MrRoyce** [comment]
Could it be that the store never completes?  This also times out:

```javascript
  it('gets the correct categories', (done) => {
    store.dispatch({ type: ActionTypes.LIST_CATEGORIES }); // start fetching
    store.whenComplete(() => { // all logic has completed
      console.log('it is done!!');
      done();
    });
  });
```

And this fails also with the timeout error
```javascript
  it('gets the correct categories', (done) => {
    store.dispatch({ type: ActionTypes.LIST_CATEGORIES }); // start fetching
    store.whenComplete(() => { // all logic has completed
      expect(1).toEqual(1);
      done();
    });
  });
```

**Comment by jeffbski** [comment]
Can you include the entire test and the logic source so I can take a look? 

You could inline it or link to a gist.

**Comment by MrRoyce** [comment]
https://gist.github.com/MrRoyce/167af6e1b02745402efc8f91d65f7a48

I'm only testing one logic function getCategoriesLogic (line 110 in CatAPI.logic.js)

Thanks for your help, let me know if I need to add more files.

**Comment by jeffbski** [comment]
I think maybe the problem is that toEqual is not a method for chai's expect.

If you use mjackson/expect `import expect from 'expect';` then toEqual is correct, but with chai's expect which is what you have, you would do `expect(store.actions).to.eql(expected);` so I believe this is causing an exception. 

Let me know if correcting the expect syntax fixes things.

**Comment by jeffbski** [comment]
I think also jest's built-in expect also would work with toEqual, so if you just took out the chai import you would also be good.

**Comment by MrRoyce** [comment]
Good catch, the chai syntax is `'to.equal(...)'`

Unfortunately it still fails with that syntax. I even tried removing the expect with:

```javascript
it('gets the correct categories', (done) => {
  store.dispatch({ type: ActionTypes.LIST_CATEGORIES }); 
  store.whenComplete(() => {
    done();
  });
});
``` 

and

```javascript
it('gets the correct categories', () => {
  store.dispatch({ type: ActionTypes.LIST_CATEGORIES }); // start fetching
  return store.whenComplete(() => { // all logic has completed
  });
});
```
and it still times out.

**Comment by jeffbski** [comment]
Add a `store.logicMiddleware.monitor$.subscribe(console.log)` before your store.dispatch so we can see what is going on inside all the logic.

```js
      store.logicMiddleware.monitor$.subscribe(console.log); // add this line
      store.dispatch(...)
      store.whenComplete ...
```

Then it should output all of the operations in redux-logic and then you can paste it here and I can help you debug.

**Comment by MrRoyce** [comment]
Here's the output:

```
  console.log node_modules/rxjs/Subscriber.js:234
    { action: { type: 'LIST_CATEGORIES' }, op: 'top' }

  console.log node_modules/rxjs/Subscriber.js:234
    { action: { type: 'LIST_CATEGORIES' },
      name: 'L(LIST_CATEGORIES)-0',
      op: 'begin' }

  console.log node_modules/rxjs/Subscriber.js:234
    { action: { type: 'LIST_CATEGORIES' },
      nextAction: { type: 'LIST_CATEGORIES' },
      name: 'L(LIST_CATEGORIES)-0',
      shouldProcess: true,
      op: 'next' }

  console.log node_modules/rxjs/Subscriber.js:234
    { nextAction: { type: 'LIST_CATEGORIES' }, op: 'bottom' }

  console.log node_modules/rxjs/Subscriber.js:234
    { action: { type: 'LIST_CATEGORIES' },
      dispAction:
       { type: 'LIST_CATEGORIES_SUCCESS',
         payload: { data: undefined, status: undefined } },
      op: 'dispatch' }

  console.log node_modules/rxjs/Subscriber.js:234
    { action:
       { type: 'LIST_CATEGORIES_SUCCESS',
         payload: { data: undefined, status: undefined } },
      op: 'top' }

  console.log node_modules/rxjs/Subscriber.js:234
    { action: { type: 'LIST_CATEGORIES' },
      name: 'L(LIST_CATEGORIES)-0',
      op: 'end' }
```

**Comment by jeffbski** [comment]
I think the payload shape is not correct. If your real httpClient is Rx.Observable.ajax then it the Observable shape that it returns is `{ response: YOURDATA }`

So in your logic you would have 
```js
process({ httpClient, CAT_API }) {
    return httpClient({ url : `${CAT_API.url}/categories`, crossDomain: true})
    .map(ret => ret.response) // ret.response is the parsed JSON
    .catch((err) => {
      console.log('Error on getting categories: ' + err);
    });
```

so in your test you can mock out httpClient as

```js
const httpClient = () => {
  return Observable.of({
    response: categories
  });
};
```

So that way we always have the same shape in both live and test circumstances, it should have a `response` property to mimic what Rx.Observable.ajax returns.

I'm guessing that since things aren't the right shape that something is getting thrown in the reducer.

**Comment by jeffbski** [comment]
Also for if httpClient is Rx.Observable.ajax you would want to set the responseType to json

```js
process({ httpClient, CAT_API }) {
    return httpClient({ url : `${CAT_API.url}/categories`, 
                        crossDomain: true,  
                        responseType: 'json'})
    .map(ret => ret.response) // ret.response is the parsed JSON
    .catch((err) => {
      console.log('Error on getting categories: ' + err);
    });
}
```

**Comment by jeffbski** [comment]
Oh, another thing I noticed is that for an Observable.catch you need to actually return an observable otherwise that is probably causing issues too.

```js
process({ httpClient, CAT_API }) {
    return httpClient({ url : `${CAT_API.url}/categories`, 
                        crossDomain: true,  
                        responseType: 'json'})
    .map(ret => ret.response) // ret.response is the parsed JSON
    .catch((err) => {
      console.log('Error on getting categories: ' + err);
      return Observable.throw(err); // return an observable
    });
}
```

**Comment by MrRoyce** [comment]
Thanks for continuing to look at this.  The logic itself seems to be
working fine as is.  I put some logging into the reducer and its getting
the correct values from the test, so I'm not sure what the issue is.

I need to work on some other stuff for a while, so I'll be putting this
aside.

The code is in a public repo if anyone wants to look at it (and likes cats
;-))

https://github.com/MrRoyce/inspirecat

**Comment by jeffbski** [comment]
I have just sent a PR that fixes your logic and test.

https://github.com/MrRoyce/inspirecat/pull/1

In a nutshell you need to specify responseType: 'json' and also Observable.catch needs to return an observable which you can do by returning Observable.throw(err) with the existing error. 

Finally the test needs to check for the same shape as what the live version emits. `{ data: categories, status: 200 }`

**Comment by MrRoyce** [comment]
Works great, thanks!

**Comment by jeffbski** [comment]
You are welcome. Glad I could help.
