### ISSUE TITLE
Test passes but lines show as not being covered

### ISSUE THREAD

**Issue by paufabregat** [jeffbski/redux-logic-test#5]
The following test passes but when I run test coverage all the lines of the logic are coloured in pink as they were not covered:

**test**
~~~javascript
let requests = [];
const store = createMockStore({
    logic: myLogic
});
describe('async actions', () => {
    before(() => {
        let xhr;
        global.XMLHttpRequest = xhr = sinon.useFakeXMLHttpRequest();
        xhr.onCreate = function (req) {
            requests.push(req);
        };
    });

    afterEach(() => {
        requests = [];
    });

    it('should get user', (done) => {
        const fakeUser = {
            config: 'user-config',
            token: 'user-token',
            userInfo: 'user-info'
        };
        const headers = {
            'Content-Type': 'application/json'
        };
        const expectedActions = [
            t.authorize(),
            t.setAuthorizedUser(fakeUser)
        ];
        store.dispatch(t.authorize());
        store.whenComplete(() => {
            store.actions.forEach((action, i) => {
                if (action.type === t.setAuthorizedUser.toString()) {
                    action.payload = fakeUser;
                }
                expect(action).to.deep.equal(expectedActions[i]);
            });
            done();
        });
        requests[0].respond(200, headers, JSON.stringify(fakeUser));
    });
});
~~~

**logic**
~~~javascript
const authorizeUser = createLogic({
    type: [t.authorize],
    process({ action }, dispatch) {
        Api.authorize().then((user) => {
            dispatch(t.setAuthorizedUser(user));
        });
    }
});
~~~

I get the following on the coverage report:
![screen shot 2017-03-16 at 15 17 14](https://cloud.githubusercontent.com/assets/4959356/24000621/0333ca14-0a5c-11e7-930a-e08354d311a3.png)
![screen shot 2017-03-16 at 15 16 53](https://cloud.githubusercontent.com/assets/4959356/24000608/f9bbdf3a-0a5b-11e7-900a-b3e59a9f26f9.png)

So it actually seems to cover the lines but they still show up coloured in pink. On the other hand other code which not involve redux-logic is covered as expected. Am I missing something?

**Comment by paufabregat** [comment]
I do not really understand why but the following stopped the described issue and it is unrelated to redux-logic:
I created another test covering more lines of another logic in the same file. If I run both tests the coverage colouring behaves as expected but if I run just the first one and I skip the second one the issue remains. 

Most likely some bug on Istanbul side.

**Comment by jeffbski** [comment]
Thanks for updating @paufabregat I know that coverage can be tricky.
