### ISSUE TITLE
Yarn warning on redux-logic peer dependency

### ISSUE THREAD

**Issue by erkiesken** [jeffbski/redux-logic-test#6]
Just noticed this after upgrading redux-logic to 0.12.0:

```
$ yarn
yarn install v0.22.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "redux-logic-test@1.0.4" has incorrect peer dependency "redux-logic@^0.11.8".
```

So maybe modify the version range on this package?

**Comment by jeffbski** [comment]
@tehnomaag Yes, thanks for mentioning that. I forgot to update that. I'll take care of that now.

**Comment by jeffbski** [comment]
Published redux-logic-test@1.0.5, hopefully that should solve your issue.

**Comment by erkiesken** [comment]
Yep warning is gone now. Thanks.

**Comment by yyynnn** [comment]
Will this package be maintained?

**Comment by jeffbski** [comment]
@yyynnn is there something that needs addressing?
