### ISSUE TITLE
failing test in store.whenComplete forces "yarn test --verbose" to exit

### ISSUE THREAD

**Issue by PEZO19** [jeffbski/redux-logic-test#7]
Hi!

I've created a react app with CRA and used yarn test --verbose to check failing tests.

I tried to alter the example code here:
https://github.com/jeffbski/redux-logic-test/blob/bc4029be87ea005e13ef4fe7d0a760e5ebbb4c93/examples/nodejs-basic/index.js#L38-L44

What I've found if
`store.whenComplete(() => ({...failing expectation here...}) `
fails, I have to manually rerun "yarn test" because it exits wit Exit code 1. See screenshot below.

Why is that happening, how can I workaround this?

Thanks,
Pezo
<img width="999" alt="screen shot 2018-03-22 at 17 53 38" src="https://user-images.githubusercontent.com/4882822/37785535-b441cbe0-2dfa-11e8-9e6b-da1d4f98cc79.png">

**Comment by PEZO19** [comment]
I could make a workaround by writing a **return** before _store.whenComplete_ , so now my test looks like this below. @jeffbski is it a proper solution? When shall we use return with store.whenComplete?

    it('test', () => {
        const store = createMockStore({...});
        store.dispatch(myAction);
        return store.whenComplete(() => {
            expect(store.actions).toEqual([...]); 
        });
    });

**Comment by jeffbski** [comment]
yes, since store.whenComplete needs to wait for things to complete, you would want to return the promise in your test so that it will wait for it.

**Comment by PEZO19** [comment]
Thanks! :)
